export const evironment={
    production:false,
    baseUrl:'https://api.realworld.io/api',
    tags:'tags',
   globalFeed:'articles',
   signin:'users/login',
   signup:"users",
   pagination:"articles",
   newArticle:'articles',
   selectedTags:"articles",
   postcomments:'articles/Create-a-new-implementation-1/comments',
   pagniation:'articles',
   settings:'user',
   yourFeed:'articles/feed',
}